- name: Updating packages based on different OS
  hosts: all
  become: true
  tasks:
    - name: Updating packages
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == "CentOS"
    
    - name: Updating packages
      apt:
        name: '*'
        state: latest
      when: ansible_distribution == "Ubuntu"