apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
    - name: mongo
      image: mongo:latest
    
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
