apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx
    demo: service
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    demo: service
  ports:
  - protocol: tcp
    port: 80
    targetport: 80
    