- name: nodejs setup
  import_role:
    name: common
    tasks_from: nodejs

- name: app-setup
  import_role:
    name: common
    tasks_from: app-setup

- name: copying cart service
  copy:
    src: cart.service
    dest: /etc/systemd/stsrem/cart.service

- name: daemon-reload
  systemd_service:
    daemon_reload: true

- name: starting service
  service: 
    name: cart
    state: started
    enabled: true

- name: downloading loading schema to mongodb
  import_role:
    name: common
    tasks_from: mongo-setup
