- name: disbaling and enabling old nodejs version
  shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y

- name: installing nodejs
  package:
    name: nodejs
    state: present
    update_cache: true
