- name: Disabling old nodejs
  command: dnf module disable nodejs -y && dnf module enable nodejs:18 -y

- name: Installing nodejs
  package:
    name: nodejs
    state: present
    update_cache: true

- name: Installing dependencies
  shell: npm Install
  args:
    chdir: /app

- name: Copying catalogue.service file
  copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service