pipeline {
    agent {
        node {
            label "Agent_1"
        }
    }
    parameters {
            choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
        }
    
    stages {
        stage ("Installing terraform") {
            steps {
                sh """
                    sudo yum update -y
                    sudo yum install -y yum-utils
                    sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
                    sudo yum install terraform -y
                """
            }
        }

        stage ("init") {
            steps {
                sh """
                    cd terraform/roboshop_dev/01_vpc
                    terraform init
                """
            }
        }

        stage ("plan") {
            steps {
                sh """
                    cd terraform/roboshop_dev/01_vpc
                    terraform plan
                """
            }
        }
        
        stage ("Deploy") {
            when {
                expression {
                    params.action == "apply"
                }
            }
            steps {
                sh """
                    terraform apply -auto-approve
                """
            }
        }

    }
}