pipeline {
    agent any

    environment {
        packageVersion = ' '
    }
    stages {
        stage ("get version from catalogue code") {
            steps {
                script {
                    def packageJson = readJSON file: 'roboshop_code/catalogue/package.json'
                    packageVersion = packageJson.version
                    echo "catalogue application version : $packageVersion"
                }
            }
        }

        stage ("install dependencies") {
            steps {
                sh """
                    dnf module disable nodejs -y
                    dnf module enable nodejs:18 -y
                    dnf install nodejs -y

                    npm install
                """
            }
        }
    }
}