apiVersion: v1
kind: Pod
metadata:
  name: pods
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

  - name: linux
    image: almalinux
    command: "sleep 300"