apiVersion: v1
kind: Pod
metadata:
  name: pods
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

  - name: linux
    image: almalinux:8
    command: ["sleep", "300"]